"""add agent_run prompt_versions

Revision ID: 20bba0bd2bda
Revises: 437406fe6001
Create Date: 2026-08-06 17:58:10.709668
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20bba0bd2bda'
down_revision: str | None = '437406fe6001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_versions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_column('prompt_versions')

    # ### end Alembic commands ###
